# Generated by Django 4.0.4 on 2022-04-21 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='user.member')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionBookMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('transaction_id', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
            ],
            options={
                'unique_together': {('transaction_id', 'book_id')},
            },
        ),
    ]
