# Generated by Django 4.0.4 on 2022-04-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('app_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_config_group', models.CharField(max_length=100)),
                ('app_config_key', models.CharField(max_length=100)),
                ('app_config_value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
